site_name: UpCreid
site_url: https://upcreid.github.io
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: indigo
    scheme: slate
  font:
    text: Roboto
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - Home: index.md

  - Blog:
      - blog/index.md

  - CheatSheet:
    - Ansible: cheat-sheet/ansible/ansible.md
    - Docker: cheat-sheet/docker/docker.md
    - Git: cheat-sheet/git/git.md
    - Shell: cheat-sheet/shell/shell.md
    - SQL: cheat-sheet/sql/sql.md
    - Tmux: cheat-sheet/tmux/tmux.md
    - Vagrant: cheat-sheet/vagrant/vagrant.md
    - VsCode: cheat-sheet/vscode/vscode.md

  - Games:
    - "StarCraft 2":
      - Params: games/starcraft2/params/starcraft2.md
    - Path of Exile 2:
        - Params: games/poe2/params/poe2_params.md
        - Builds:
            - "Frost Nova Elementalist": games/poe2/builds/frost_nova_elementalist.md
            - "Bombarding Minions Infernalist": games/poe2/builds/poe2_bombarding_minion_infernalist.md
