site_name: /void !
site_description:  personal documentation - Guides, cheat sheets and technical resources
site_author: upcreid
site_url: https://upcreid.github.io/

repo_url: https://github.com/upcreid/upcreid.github.io
repo_name: upcreid/upcreid.github.io

theme:
  name: material
  
  # Configuration des couleurs (identique au site officiel)
  palette:
    # Palette pour le mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette pour le mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Police (identique au site officiel)
  font:
    text: Roboto
    code: Roboto Mono
  
  # Logo et icônes
  logo: assets/logo.png
  favicon: assets/logo.png
  
  # Fonctionnalités activées (identique au site officiel)
  features:
    # Announcements
    - announce.dismiss
    
    # Navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    
    # Table des matières
    - toc.follow
    
    # Recherche
    - search.highlight
    - search.share
    - search.suggest
    
    # Header
    - header.autohide
    
    # Contenu
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - content.footnote.tooltips
    
    # Onglets de contenu
    - content.tabs.link

# Extensions Markdown (configuration professionnelle)
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: blog
      post_date_format: long
      pagination_per_page: 10

# Customisation CSS
extra_css:
  - stylesheets/extra.css

# JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Variables extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/upcreid
      name: GitHub Profile
  
  generator: false

# Navigation
nav:
  - Overview: index.md
  - Blog:
    - Overview: blog/index.md
  - CheatSheet:
    - Overview: cheat-sheet/index.md
    - Python Build: cheat-sheet/python-build/python-build.md
    - FastAPI: cheat-sheet/fastapi/fastapi.md
    - Go (Golang): cheat-sheet/golang/golang.md
    - Hugo: cheat-sheet/hugo/hugo.md
    - C# & .NET: cheat-sheet/csharp-dotnet/csharp-dotnet.md
    - Docker: cheat-sheet/docker/docker.md
    - Kubectl: cheat-sheet/kubectl/kubectl.md
    - K9s: cheat-sheet/k9s/k9s.md
    - Git: cheat-sheet/git/git.md
    - Grafana: cheat-sheet/grafana/grafana.md
    - Prometheus: cheat-sheet/prometheus/prometheus.md
    - Linux File System: cheat-sheet/linux-filesystem/linux-filesystem.md
    - Shell: cheat-sheet/shell/shell.md
    - curl: cheat-sheet/curl/curl.md
    - netcat: cheat-sheet/netcat/netcat.md
    - Ansible: cheat-sheet/ansible/ansible.md
    - Slidev: cheat-sheet/slidev/slidev.md
    - SQL: cheat-sheet/sql/sql.md
    - Tmux: cheat-sheet/tmux/tmux.md
    - Vagrant: cheat-sheet/vagrant/vagrant.md
    - Terraform: cheat-sheet/terraform/terraform.md
    - Vim: cheat-sheet/vim/vim.md
    - Macos File System: cheat-sheet/macos-filesystem/macos-filesystem.md
  - Games:
    - Overview: games/index.md
    - Path of Exile 2:
      - games/poe2/index.md
      - Build Guides:
        - Ballista Banner Tactician: games/poe2/builds/ballista-banner-tactician.md
      - Parameters: games/poe2/params/poe2_params.md
    - StarCraft2:
      - games/starcraft2/index.md
      - Parameters: games/starcraft2/params/starcraft2.md